gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Encuentre la tarjeta perfecta
description: Entre tantas tarjetas ¿Cuál es la que mejor se adapta a sus necesidades?

# Name of project on Github
baseurl:

# Build settings
markdown: kramdown
