gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Encuentre la tarjeta perfecta
description: Entre tantas tarjetas ¿Cuál es la que mejor se adapta a sus necesidades?

# Name of project on Github
baseurl:

image_path: https://www.baccredomatic.com/sites/default/files/

# Build settings
markdown: kramdown

assets:
  compress:
    css: default
    js: default
  cache: false
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: default
  sources:
    - "_assets/folder"
