gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Encuentre la tarjeta perfecta
description: Entre tantas tarjetas ¿Cuál es la que mejor se adapta a sus necesidades?

# Name of project on Github
baseurl:

# Build settings
markdown: kramdown

assets:
  compress:
    css: false
    js: false
  cache: false
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: false
  sources:
    - "_assets/folder"
