gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Encuentre la tarjeta perfecta
description: Entre tantas tarjetas ¿Cuál es la que mejor se adapta a sus necesidades?

# Name of project on Github
baseurl:

# Build settings
markdown: kramdown

contentful:
  spaces:
    - tarjetas:
        space: 9cds0lha1plv
        access_token: 9f6c8ccc9a4c169661818d45d3869b9644caf0261e1dbd482632f3e44ac93b36
